NICK = "ButtBot"
SERVER = ("irc.choopa.net", 6667)
CHANS = ["#D-S"]
OWNER = "pheni"
PREFIX = "!"
TAGLINES = ['MODULAR IRC PROCESSING SHIT', "MULTIPLE IDENTITY PATRIOT SYNDROME", "MEGA INFRACTIONS PER SECOND", "MASSIVE INCEST PORN SLAVE"]
NICKSERV = False

def H(hook, desc): return PREFIX+hook+" "+desc
